#!/bin/bash

for ppid in $(cat ans4 | awk '{print $5}' | sort -n -u)
do
grep -e "Parent_ProcessID= $ppid " ans4 >> ans5
echo -n "Average_Sleeping_Children_of_ParentID=$ppid is " >> ans5
grep -e "Parent_ProcessID= $ppid " ans4 | awk '{s += $8} {i += 1} END {print s/i}' >> ans5
done
