#! /bin/bash

mode="+"
num=1

(tail -f pipe) | 
while true; do 
	read line;
	echo "$line"
        if [[ "$line" == "+" ]]
	then
		mode="+"
	elif [[ "$line" == "*" ]]
	then
		mode="*"
	elif [[ "$line" == "QUIT" ]]
	then
		echo "exit"
       		killall tail
        	exit 0
	elif [[ "$line" =~ ^-?[0-9]+$ ]]
	then
		case $mode in
                "+")
                    echo "Sum" $num "and " $line						
                    num=$(($num + $line))
                    echo "result " $num
                    ;;
                "*")
                    echo "Mult" $num "and " $line						
                    num=$(($num * $line))
                    echo "result " $num
                    ;;
        	esac

	else
		echo "INCORRECT input"	
		killall tail
        	exit 1
	fi
done
